/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ifanow;

import org.junit.Test;
import static org.junit.Assert.*;

public class IFANOWApplicationTest {
    @Test public void testSomeMethod() {
//    	IFANOWApplication classUnderTest = new IFANOWApplication();
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
