/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ifanow;

import java.time.ZoneId;
import java.util.TimeZone;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.core.env.Environment;

@SpringBootApplication
public class IFANOWApplication {
    public boolean someLibraryMethod() {
        return true;
    }
    
	public static void main(String[] args) {
	    TimeZone zone = TimeZone.getTimeZone(ZoneId.of("UTC"));
	    TimeZone.setDefault(zone);
		SpringApplication.run(IFANOWApplication.class, args);
	}
	
	@Autowired
	Environment environment;
	
    @PostConstruct 
    private void init(){
//    	Util.init(environment);
    }
}
